name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        redis:
            image: redis
            ports:
              - 6379:6379

    steps:
      - name: Install redis cli
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      - name: Print Variable
        run: echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test redis
        run: redis-cli -h localhost -p 6379 ping
    
      - name: setup
        uses: actions/setup-node@v4
        with:
            node-version: '18'
      
      - name: Instalar dependencias
        run: npm install
    
      - name: Run test
        run: npm run test
    
      - name: Build Page
        run: npm run build
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/    
  
  deploy:
    if: ${{ always()}}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4